version: '2'
services:
  web:
    image: keopx/apache-php:7.0
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - ../:/var/www/html
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./config/php/7.0/php.ini:/etc/php/7.0/apache2/php.ini
      - ./config/apache2:/etc/apache2
    working_dir: /var/www/html
    environment:
      - PHP_SENDMAIL_DOMAIN=mail-student.le-101.fr:25
  mysql:
    image: keopx/mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=Matcha
      - MYSQL_USER=angauber
      - MYSQL_PASSWORD=angauber
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "6690:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql

